# User Input Code
eye = input("What character is to be used for an eye?")
print(" ########## ")
print(" # {} {}  # ").format(eye)
print(" #        # ")
print(" ########## ")
print("     ##     ")
print("     ##     ")
print("############")
print("#          #")
print("#          #")
print("#          #")
print("############")
print("  #      #  ")
print("  #      #  ")